language: ruby

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.1
  - 2.6.0-preview1
  - jruby-9.1.16.0

matrix:
  exclude:
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.6.0-preview1
      gemfile: gemfiles/rails_4.2.gemfile
  allow_failures:
    - rvm: 2.6.0-preview1
    - rvm: jruby-9.1.16.0
    - gemfile: gemfiles/rails_5.2.gemfile

notifications:
  email: false

bundler_args: --without development

services:
  - mongodb

sudo: false

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
