language: ruby

gemfile:
  - gemfiles/mongoid_5.gemfile
  - gemfiles/mongoid_6.gemfile
  - gemfiles/mongoid_7.gemfile

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.0-preview1
  - jruby-9.1.17.0

matrix:
  exclude:
    - rvm: 2.4.4
      gemfile: gemfiles/mongoid_5.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/mongoid_5.gemfile
    - rvm: 2.6.0-preview1
      gemfile: gemfiles/mongoid_5.gemfile
    - rvm: jruby-9.1.17.0
      gemfile: gemfiles/mongoid_7.gemfile
  allow_failures:
    - rvm: 2.6.0-preview1
    - rvm: jruby-9.1.17.0

bundler_args: --without development

services:
  - mongodb

sudo: false

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
